name: packedup
description: packedup_flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_facebook_auth: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/


  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin/Cabin-Regular.ttf
        - asset: assets/fonts/Cabin/Cabin-Medium.ttf
        - asset: assets/fonts/Cabin/Cabin-Bold.ttf

    - family: FrankRuhlLibre
      fonts:
        - asset: assets/fonts/Frank_Ruhl_Libre/FrankRuhlLibre-Regular.ttf
        - asset: assets/fonts/Frank_Ruhl_Libre/FrankRuhlLibre-Medium.ttf
        - asset: assets/fonts/Frank_Ruhl_Libre/FrankRuhlLibre-Bold.ttf
#    - family: SourceSansPro
#      fonts:
#        - asset: fonts/SourceSansPro/SourceSansPro-Regular.ttf
#        - asset: fonts/SourceSansPro/SourceSansPro-Light.ttf
#          weight: 100
